### ISSUE TITLE
Broken integration - Invalid Token

### ISSUE THREAD

**Issue by pbraswell** [tkgospodinov/omniauth-fitbit#13]
Hi,
I had at one point this gem integrated with a RoR application and it was working just fine, then it wasn't.  We're getting the following errors, any idea what the problem might be? :+1: 

This page is no longer valid. It looks like you provided an invalid token or someone already used the token you provided. Please return to the site or application which sent you to this page and try again.

Thank you!!!
-Peter

**Comment by tkgospodinov** [comment]
It could have something to do with the change described here -- https://groups.google.com/forum/#!msg/fitbit-api/KKEZhAQKXeQ/y2FhVYQe7KsJ

I haven't received any other reports, so I'll close the issue.
