### ISSUE TITLE
Is OAuth 2 supported?

### ISSUE THREAD

**Issue by gupta-ankit** [tkgospodinov/omniauth-fitbit#19]
As I understand, this gem supports the OAuth 1.0

As Fitbit is moving from OAuth1 to OAuth2, is there an update planned to support OAuth 2?

**Comment by Willgg** [comment]
Hi guys,
I have seen Fitbit is moving to oAuth 2.0 by April 2016. Any answer to the question of gupta-ankit ?
Thanks

**Comment by rcyep87** [comment]
I too am wondering if there are plans for OAuth2 to be supported with this gem.

**Comment by gupta-ankit** [comment]
In case this one does not update, there is a new gem for oauth2

https://github.com/codebender/omniauth-fitbit-oauth2

Also, I am writing a clone of fitgem to support OAuth2

https://github.com/gupta-ankit/fitgem_oauth2

**Comment by rcyep87** [comment]
Thanks gupta-ankit!

**Comment by tkgospodinov** [comment]
I haven't done any work on migrating this gem to oauth2 yet, but I'll look into it. In the meantime, pull requests are welcome if anyone has the time to do it before I get to it.

Thanks.

**Comment by tkgospodinov** [comment]
Good news - I have staged a 2.0.0 version of the gem in the oauth2 branch and I'm planning to merge and release it soon.

**Comment by tkgospodinov** [comment]
Released omniauth-fitbit-2.0.0 with support for OAuth2
