### ISSUE TITLE
OAuth 2 not supported

### ISSUE THREAD

**Issue by brittanykohler** [tkgospodinov/omniauth-fitbit#21]
Today during Fitbit's hour blackout period of OAuth 1.0a, my omniauth stopped working. Does this app support OAuth 2.0? If so, is there anything specific I need to configure to use OAuth 2.0 vs OAuth 1.0a?

**Comment by tkgospodinov** [comment]
Yes, it does. You just need to upgrade to version 2.0.0 of the gem.
